#!/usr/bin/python                                                               
# Better cat
# Extra new line
import sys                                                                      
lines=sys.stdin.readlines()                                                     
for l in lines:
	print l
