#!/usr/bin/python                                                               
# Better cat
# Extra new line
import sys                                                                      

if (len(sys.argv[1:])):
	for f in sys.argv[1:]:
		fh=open(f,'r')
		for l in fh.readlines():
			print l,
else:
	for l in sys.stdin.readlines():
		print l,


